routes/web.php
<?php

use App\LeaveType;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\LeaveTypeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

//****Gruop the Route that need to be log in before access the website****//
Route::middleware(['auth'])->group(function () {

    Route::resource('user', UserController::class);
    //user profile
    Route::get('/', 'UserController@profile')->name('profile');
    //team's user
    Route::get('department', 'UserController@teamIndex')->name('team-index');


    Route::resource('requests', RequestLeaveController::class)->only(['index']);
    Route::resource('profile/request', RequestLeaveController::class)->except(['index']);
    //all requests of the user
    Route::get('profile/list-request', 'RequestLeaveController@listRequest')->name('list-request');
    // {department?} คือเราสร้างพารามิตเตอร์ให้url สามารถรับค่าได้ แล้วก็ ? ที่อยู่ข้างหลังแปลว่า มีหรือไม่มีก็ได้
    //team's requests
    Route::get('team-request/{department?}', 'RequestLeaveController@teamRequest')->name('team-request');


    Route::get('/leave-type', [LeaveTypeController::class, 'index'])->name('leave-type');
    Route::get('/leave-type/create', [LeaveTypeController::class, 'create'])->name('create-leave-type');
    Route::post('/leave-type', [LeaveTypeController::class, 'store']);
    Route::get('leave-type/{id}/edit', [LeaveTypeController::class, 'edit'])->name('edit-leave-type');
    Route::put('/leave-type/{id}', [LeaveTypeController::class, 'update'])->name('update-leave-type');
    Route::delete('/leave-type/{id}', [LeaveTypeController::class, 'destroy'])->name('delete-leave-type');

});

resources/views/request/create.blade.php
@extends('layouts.app')

@section('content')
{{-- Laravel Collective --}}
<div class="container">
    <div class="row justify-content-center">
    {{-- Error messages when missing fields --}}
    @if ($errors->all())
        <ul class="alert alert-danger">
            @foreach ($errors->all() as $error )
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif
    <div class="col-lg-6">
    {{-- A Request Form --}}
    {{-- open a form --}}
    {{ Form::open(['route' => 'request.store', 'method' => 'POST'],) }}
        {{-- <div class="row"> --}}
        

            <div class="form-group">
                {!! Form::label('which is your leave type?') !!}
                {!! Form::select('type_id', ['' => '--Select--'] + $leave_type, null, ['class' => 'form-control form-type']) !!} 
            </div>
            {{-- [] + [] = one [] --}}

            <div class="form-group">
                {!! Form::label('Start from ?') !!}
                {!! Form::date('from_date', \Carbon\Carbon::now(), ['class' => 'form-control start-leave-date']) !!} 
            </div>
            <div class="form-group">
                {!! Form::checkbox('half_day[]', 'morning leave') !!} 
                {!! Form::label('morning leave', 'morning leave', ['class' => 'text-lowercase']) !!}
            </div>
            <div class="form-group">
                {!! Form::checkbox('half_day[]', 'afternoon leave') !!} 
                {!! Form::label('afternoon leave', 'afternoon leave', ['class' => 'text-lowercase']) !!}
            </div>


            <div class="form-group">
                {!! Form::label('Returning at ?') !!}
                {!! Form::date('to_date', \Carbon\Carbon::now(), ['class' => 'form-control end-leave-date']) !!} 
            </div>
            <div class="form-group">
                {!! Form::checkbox('half_day[]', 'return in the afternoon') !!} 
                {!! Form::label('return in the afternoon', 'return in the afternoon', ['class' => 'text-lowercase']) !!}
            </div>

            <div class="form-group">
                {!! Form::label('Why you ask for leaving?') !!}
                {!! Form::text('reason', " ",['class' => 'form-control reason-to-leave']) !!} 
            </div>

            <div class="form-group">
                {!! Form::label('What is your pending responsibility?') !!}
                {!! Form::text('pending_responsibilities', "",['class' => 'form-control pending-responsibilities']) !!} 
            </div>

            <div class="form-group">
                {!! Form::submit('SUBMIT') !!}
            </div>

        </div>
        </div>
    </div>
</div>
@endsection

resources/views/request/edit.blade.php
@extends('layouts.app');
@section ('content');

    <div class="container">
        <div class="row justify-content-center">
            <div class="card" style="width:28rem;">
                <div class="card-body">
                    <h3 class="card-title text-center">{{ $data->user->firstname }} {{ $data->user->surname }}</h5>
                        <ul class="list-group">
                            <li class="list-group-item">Request for: <span>{{ $data->type->name }}</span></li>
                            <li class="list-group-item">Strat date: <span>{{ date("d-m-Y", strtotime($data->from_date)) }}</span></li>
                            <li class="list-group-item">Return date: <span>{{ date("d-m-Y", strtotime($data->to_date)) }}</span></li>
                            <li class="list-group-item">Total: <span>{{ $data->total_days}} day(s)</span></li>
                            <li class="list-group-item">Reason to leave: <span>{{ $data->reason}}</span></li>
                            <li class="list-group-item">Pending Responsibility: <span>{{ $data->pending_responsibilities}}</span></li>
                            
                            @can('can-approve', $data)
                            <li class="list-group-item">
                                @switch ($user_role)
                                    @case ($user_role->isAdmin())
                                        {!! Form::open(['action' => ['RequestLeaveController@update', $data->id], 'method' => 'PUT']) !!}
                                            {{-- Approval from team's manager --}}
                                            {!! Form::label('status_manager', 'Status (from manager): ') !!}
                                            {!! Form::select('status_manager', ['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected'], $data->status_manager) !!}                                        
                                            <br>{{-- Approval from HR --}}
                                            {!! Form::label('status_hr', 'Status (from HR): ') !!}
                                            {!! Form::select('status_hr', ['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected'], $data->status_hr) !!}                                    
                                            <br>
                                            {!! Form::submit('Save') !!}
                                        {!! Form::close() !!}
                                    @break
                                    @case ($user_role->isHr())
                                        {!! Form::open(['action' => ['RequestLeaveController@update', $data->id], 'method' => 'PUT']) !!}
                                            {!! Form::label('status_hr', 'Status (from HR): ') !!}
                                            {!! Form::select('status_hr', ['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected'], $data->status_hr) !!}                                       
                                            {!! Form::submit('Save') !!}
                                        {!! Form::close() !!}
                                    @break
                                    @case ($user_role->isManager())
                                        {!! Form::open(['action' => ['RequestLeaveController@update', $data->id], 'method' => 'PUT']) !!}
                                            {!! Form::label('status_manager', 'Status (from manager): ') !!}
                                            {!! Form::select('status_manager', ['pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected'], $data->status_manager) !!}                                       
                                            {!! Form::submit('Save') !!}
                                        {!! Form::close() !!}
                                    @break
                                @endswitch
                            </li>
                            @endcan
                        </ul>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/request/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h2 align="center"> Request </h2>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Request date</th>
                    <th scope="col">Nickname</th>
                    <th scope="col">Department</th>
                    <th scope="col">Leave Type</th>
                    <th scope="col">Start</th>
                    <th scope="col">Return</th>
                    <th scope="col">Total day(s)</th>
                    <th scope="col">Manager Approval</th>
                    <th scope="col">HR Approval</th>
                    <th scope="col"></th>
                
                </tr>
            </thead>
            <tbody>
            {{-- to show data, will use @foreach loop --}}
                @foreach ($requests as $row) {{-- เอาขอมูลมาจากตัวแปรอาเรย์ $data ในController แล้วก็ให้โชว์as $row โชว์ทีละตัว--}}
                    
                        <tr>
                            <td scope="row">{{ $loop->iteration }}</td>
                            <td>{!! date("d-m-Y H:i:s", strtotime($row->created_at)) !!}</td>
                            <td>{{ $row->user->nickname }}</td>
                            <td>{{ $row->user->department }}</td>
                            <td>{{ $row->type->name }}</td>
                            <td>{{ date("d-m-Y", strtotime($row->from_date)) }}</td>
                            <td>{{ date("d-m-Y", strtotime($row->to_date)) }}</td>
                            <td>{{ $row->total_days }}</td>
                             @if ($row->status_manager == "rejected")
                                <td class="table-danger">{{ $row->status_manager }}</td>
                            @elseif ($row->status_manager == "approved")
                                <td class="table-success">{{ $row->status_manager }}</td>
                            @else
                                <td class="table-light">{{ $row->status_manager }}</td>
                            @endif
                            @if ($row->status_hr == "rejected")
                                <td class="table-danger">{{ $row->status_hr }}</td>
                            @elseif ($row->status_hr == "approved")
                                <td class="table-success">{{ $row->status_hr }}</td>
                            @else
                                <td class="table-light">{{ $row->status_hr }}</td>
                            @endif

                            <td><a class="btn btn-outline-info" href="{{ route('request.edit', $row->id) }}">Permission</a></td>
                            <td>
                                <form action="{{ route('request.destroy', $row->id) }}" method="POST">
                                    @csrf @method('DELETE')
                                    <input type="submit" value="Delete" data-name="{{ $row->user->nickname }}" class="btn btn-outline-danger deleteForm"
                                    onclick="return confirm('Do you want to delete {{$row->user->nickname}} ?')">
                                </form>
                            </td>

                        </tr>
                    
                @endforeach
                   
            </tbody>
        </table>
    </div>

@endsection

resources/views/request/list-request.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h2 align="center"> Request </h2>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Manager Status</th>
                    <th scope="col">HR Status</th>
                    <th scope="col">Nickname</th>
                    <th scope="col">Leave Type</th>
                    <th scope="col">Start leaving</th>
                    <th scope="col">Return at</th>
                    <th scope="col">Total day(s)</th>
                    <th scope="col">Reason to leave</th>
                    <th scope="col">Pending Responsibility</th>          
                </tr>
            </thead>
            <tbody>
            {{-- to show data, will use @foreach loop --}}
                @foreach ($data as $row) {{-- เอาขอมูลมาจากตัวแปรอาเรย์ $data ในController แล้วก็ให้โชว์as $row โชว์ทีละตัว--}}
                    <tr>
                        @if ($row->status_manager == "rejected")
                            <td class="table-danger">{{ $row->status_manager }}</td>
                        @elseif ($row->status_manager == "approved")
                            <td class="table-success">{{ $row->status_manager }}</td>
                        @else
                            <td class="table-light">{{ $row->status_manager }}</td>
                        @endif
                        @if ($row->status_hr == "rejected")
                            <td class="table-danger">{{ $row->status_hr }}</td>
                        @elseif ($row->status_hr == "approved")
                            <td class="table-success">{{ $row->status_hr }}</td>
                        @else
                            <td class="table-light">{{ $row->status_hr }}</td>
                        @endif
                            <td>{{ $row->user->nickname }}</td>
                            <td>{{ $row->type->name }}</td>
                            <td>{{ date("d-m-Y", strtotime($row->from_date)) }}</td>
                            <td>{{ date("d-m-Y", strtotime($row->to_date)) }}</td>
                            <td>{{ $row->total_days }}</td>
                            <td>{{ $row->reason }}</td>
                            <td>{{ $row->pending_responsibilities }}</td>
                                                      
                    </tr>
                @endforeach
                   
            </tbody>
        </table>
    </div>

@endsection

resources/views/request/show.blade.php
@extends('layouts.app');
@section ('content');

    <div class="container">
        <div class="row justify-content-center">
            <div class="card" style="width:28rem;">
                <div class="card-body">
                    <h3 class="card-title text-center">{{ $data->user->firstname }} {{ $data->user->surname }}</h5>
                        <ul class="list-group">
                            <li class="list-group-item">Request for: <span>{{ $data->type->name }}</span></li>
                            <li class="list-group-item">Strat date: <span>{{ date("d-m-Y", strtotime($data->from_date)) }}</span></li>
                            <li class="list-group-item">Return date: <span>{{ date("d-m-Y", strtotime($data->to_date)) }}</span></li>
                            <li class="list-group-item">Total: <span>{{ $data->total_days}} day(s)</span></li>
                            <li class="list-group-item">Reason to leave: <span>{{ $data->reason}}</span></li>
                            <li class="list-group-item">Pending Responsibility: <span>{{ $data->pending_responsibilities}}</span></li>
                            <li class="list-group-item">Status (manager, hr): <span>{{ $data->status_manager . ", " . $data->status_hr }}</span></li>
                        </ul>
                    
                        
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/request/team-request.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h2 align="center"> Request </h2>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">Request date</th>
                    <th scope="col">Nickname</th>
                    <th scope="col">Department</th>
                    <th scope="col">Leave Type</th>
                    <th scope="col">Start</th>
                    <th scope="col">Return</th>
                    <th scope="col">Total day(s)</th>
                    <th scope="col">Action</th>
                    <th scope="col">Manager Approval</th>
                    <th scope="col">HR Approval</th>
                    
                </tr>
            </thead>
            <tbody>
            @can('can-see-team-request', $requests)
            {{-- to show data, will use @foreach loop --}}
                @foreach ($requests as $row) {{-- เอาขอมูลมาจากตัวแปรอาเรย์ $data ในController แล้วก็ให้โชว์as $row โชว์ทีละตัว--}}
                    {{-- @can('can-view-only-user-request', $row) --}}
                        <tr>
                            <td scope="row">{{ $loop->iteration }}</td>
                            <td>{!! date("d-m-Y H:i:s", strtotime($row->created_at)) !!}</td>
                            <td>{{ $row->user->nickname }}</td>
                            <td>{{ $row->user->department }}</td>
                            <td>{{ $row->type->name }}</td>
                            <td>{{ date("d-m-Y", strtotime($row->from_date)) }}</td>
                            <td>{{ date("d-m-Y", strtotime($row->to_date)) }}</td>
                            <td>{{ $row->total_days }}</td>
                             <td><a class="btn btn-outline-info" href="{{ route('request.edit', $row->id) }}">Permission</a></td>
                             @if ($row->status_manager == "rejected")
                                <td class="table-danger">{{ $row->status_manager }}</td>
                            @elseif ($row->status_manager == "approved")
                                <td class="table-success">{{ $row->status_manager }}</td>
                            @else
                                <td class="table-light">{{ $row->status_manager }}</td>
                            @endif
                            @if ($row->status_hr == "rejected")
                                <td class="table-danger">{{ $row->status_hr }}</td>
                            @elseif ($row->status_hr == "approved")
                                <td class="table-success">{{ $row->status_hr }}</td>
                            @else
                                <td class="table-light">{{ $row->status_hr }}</td>
                            @endif
                                                      
                        </tr>
                    {{-- @endcan --}}
                @endforeach
            @endcan
            </tbody>
        </table>
    </div>

@endsection