routes/web.php
<?php

use App\LeaveType;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\LeaveTypeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

//****Gruop the Route that need to be log in before access the website****//
Route::middleware(['auth'])->group(function () {

    Route::resource('user', UserController::class);
    //user profile
    Route::get('/', 'UserController@profile')->name('profile');
    //team's user
    Route::get('department', 'UserController@teamIndex')->name('team-index');


    Route::resource('requests', RequestLeaveController::class)->only(['index']);
    Route::resource('profile/request', RequestLeaveController::class)->except(['index']);
    //all requests of the user
    Route::get('profile/list-request', 'RequestLeaveController@listRequest')->name('list-request');
    // {department?} คือเราสร้างพารามิตเตอร์ให้url สามารถรับค่าได้ แล้วก็ ? ที่อยู่ข้างหลังแปลว่า มีหรือไม่มีก็ได้
    //team's requests
    Route::get('team-request/{department?}', 'RequestLeaveController@teamRequest')->name('team-request');


    Route::get('/leave-type', [LeaveTypeController::class, 'index'])->name('leave-type');
    Route::get('/leave-type/create', [LeaveTypeController::class, 'create'])->name('create-leave-type');
    Route::post('/leave-type', [LeaveTypeController::class, 'store']);
    Route::get('leave-type/{id}/edit', [LeaveTypeController::class, 'edit'])->name('edit-leave-type');
    Route::put('/leave-type/{id}', [LeaveTypeController::class, 'update'])->name('update-leave-type');
    Route::delete('/leave-type/{id}', [LeaveTypeController::class, 'destroy'])->name('delete-leave-type');

});

app/User.php
<?php

namespace App;
use Illuminate\Support\Str;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    const user_roles = [
        'admin'     => 'Admin',
        'hr'        => 'Human Resource',
        'manager'   => 'Team Manager',
        'user'      => 'User'
    ];
    
    const departments = [
        'operations'            => 'Operations',
        'strategy-and-ideation' => 'Strategy and Ideation',
        'video-production'      => 'Video Production',
        'social-media'          => 'Social Media',
        'graphic-design'        => 'Graphic Design',
        'tech-lab'              => 'Tech Lab',
        'client-services'       => 'Client Services'
    ];

    use Notifiable;

    /**
     * The attributes that are mass assignable!!!!!.
     *
     * @var array
     */
    protected $fillable = [
        'firstname', 
        'surname', 
        'nickname',
        'thai_name',
        'first_day_of_work',
        'position', 
        'department', 
        'phone_number', 
        'date_of_birth', 
        'email', 
        'password',
        'user_role',
        'line_id',
        'emergency_name',
        'emergency_number',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'first_day_of_word',
        'date_of_birth',
    ];

    // Mutators -> capitalize input data
    public function setFirstnameAttribute($value) {
        $this->attributes['firstname'] = Str::ucfirst($value);
    }

    public function setSurnameAttribute($value) {
        $this->attributes['surname'] = Str::ucfirst($value);
    }

    // User has many requests.
    public function requestleaves() {
        return $this->hasMany(RequestLeave::class);
    }

    public function isAdmin() {
        return $this->user_role === 'admin';
    }

    public function isManager() {
        return $this->user_role === 'manager';
    }

    public function isHr() {
        return $this->user_role === 'hr';
    }

    public function isUser() {
        return $this->user_role === 'user';
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\LeaveType;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;
use App\RequestLeave;
use Illuminate\Support\Carbon;

class UserController extends Controller
{

    /**
     * Display a listing of the team's users.
     * only team's manager can see this list.
     *
     * @return \Illuminate\Http\Response
     */
    public function teamIndex()
    {
        //get current user (manager)
        $current_department = Auth::user()->department;
        //need to use data where manager department = user's department
        $data = User::where('department', $current_department)->get();
        // $this->authorize('viewTeam', $data);
        // var_dump($data);
        return view('user.team-index', compact(['data', 'current_department']));
        
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //need to use data from user model and save them to $data
        $data = User::orderBy('firstname', 'asc')->orderBy('department', 'asc')->get();
        // print_r($data);
        // return json_decode($data);
            return view('user.index', compact(['data']));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('auth.register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'firstname' => 'required|max:20',
            'surname' => 'required|max:20',  //check at users table
            'nickname' => 'required|max:20',
            'first_day_of_work' => 'required|date',
            'department' => 'required|in:' . implode(',', array_keys(User::departments)),
            'phone_number' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
            'date_of_birth' => 'required|date',
            'email' => 'required|email|max:100|unique:users',
        ]);
        
        //save data through User Model
        User::create($request -> all());
            return redirect(route('profile'));

    }

    /**
     * Display the profile.
     *
     * @return \Illuminate\Http\Response
     */
    public function profile()
    {
        $current_user = Auth::user()->id;
        // var_dump($current_user);
        //using query in show method.

        
        return $this->show($current_user);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $profile = User::findOrFail($id);  //parameter that is not existing will lead to 404.
        $this->authorize('view', $profile);

        $now = Carbon::now();
        $startDate = Carbon::parse($profile->first_day_of_work);
        // x = different years btw now and first_day_of_work
        $x = $now->diffInYears($startDate);
        // $x will be used to find the year that the staff is working.
        // so, $x + 1 will be the next working year
        $anniversary = $startDate->addYears($x);
        // dd($anniversary);
        
        //select * from leave_types table
        //$types = LeaveType::all()
        //select request_leaves join id = type_id Sun total_days
        $types = $profile->requestLeaves()
            ->join('leave_types', 'type_id', '=', 'leave_types.id')
            ->selectRaw('SUM(total_days) as used_days') //Aggregation
            ->whereBetween('from_date', [$anniversary, $now]) //btw now and the anniversary first day of work
            ->addSelect('leave_types.name', 'allowance')
            ->groupBy('leave_types.name', 'allowance') 
            ->get();
            // dd($types);
        return view('user.profile', [
            'user' => $profile,
            'types' => $types
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //get the details from User($id)
        $data = User::find($id);
        $this->authorize('update', $data);
        return view('user.edit', compact(['data']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'firstname' => 'required|max:20',
            'surname' => 'required|max:20',
            'nickname' => 'required|max:20',
            'first_day_of_work' => 'required|date',
            'department' => 'required|in:' . implode(',', array_keys(User::departments)),
            'user_role' => 'in:admin,manager,user,hr',
            'phone_number' => 'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
            'date_of_birth' => 'required|date',
            'email' => 'required|email|max:100',
        ]);
        
        // dd($request->all());
        //flash messages tell user that the request succeeded
        session()->flash('success', $request->firstname . " " . 'has been updated successfully');
        //save data through Usre Model
        
        User::find($id)->update($request->all());

        if(Auth::user()->user_role === 'admin') {
            return redirect(route('user.index'));   
        } else {
            return redirect(route('profile'));
        }       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find(1);

        $user->delete();
        //flash messages after deleted
        session()->flash('delete', $user->firstname . " " . 'has been deleted');
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    {{-- will apply Laravel Collective for this create Form -> https://laravelcollective.com/docs/6.x/html --}}

    <div class="container">
        <div class="row justify-content-center">
            {{-- Error messages --}}
            @if ($errors->all())
                <ul class="alert alert-danger">
                    @foreach ($errors->all() as $error )
                        <li>
                            {{$error}}
                        </li>            
                    @endforeach
                </ul>
            @endif
            <div class="col-xs-12 col-sm-6 col-md-6">
                {!! Form::open(['action' => ['UserController@update', $data->id], 'method'=>'PUT']) !!} {{--After submit where the action will take--}}
                    <div class="form-group">
                        {!! Form::label('First Name') !!}
                        {!! Form::text('firstname', $data->firstname, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>

                    <div class="form-group">
                        {!! Form::label('Last Name') !!}
                        {!! Form::text('surname', $data->surname, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>

                    <div class="form-group">
                        {!! Form::label('Fullname in Thai') !!}
                        {!! Form::text('thai_name', $data->thai_name, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>

                    <div class="form-group">
                        {!! Form::label('Start Working at') !!}
                        {!! Form::date('first_day_of_work', $data->first_day_of_work, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>
                    
                    <div class="form-group">
                        {!! Form::label('NICKNAME') !!}
                        {!! Form::text('nickname', $data->nickname, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>
                    
                    <div class="form-group">
                        {!! Form::label('Department') !!}
                        {!! Form::select('department', ['' => '--Select--'] + \App\User::departments, $data->department, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>
                @can ('can-update-role', $data)
                    <div class="form-group">
                        {!! Form::label('User Role') !!}
                        {!! Form::select('user_role', \App\User::user_roles, $data->user_role, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>
                @endcan    
                    <div class="form-group">
                        {!! Form::label('Email Adress') !!}
                        {!! Form::email('email', $data->email, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>

                    <div class="form-group">
                        {!! Form::label('Line ID') !!}
                        {!! Form::email('line_id', $data->line_id, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>
                    
                    <div class="form-group">
                        {!! Form::label('Phone') !!}
                        {!! Form::number('phone_number', $data->phone_number, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>

                    <div class="form-group">
                        {!! Form::label('Birthday') !!}
                        {!! Form::date('date_of_birth', $data->date_of_birth, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>

                    <div class="form-group">
                        {!! Form::label('Emergency Contact Name') !!}
                        {!! Form::email('emergency_name', $data->emergency_name, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>

                    <div class="form-group">
                        {!! Form::label('Emergency Contact Number') !!}
                        {!! Form::email('emergency_number', $data->emergency_number, ['class' => 'form-control']) !!} {{-- Form text (this input name, default value, class) --}}
                    </div>

                    {{ Form::submit('UPDATE') }}
                    <a href="/user" class="btn">BACK</a>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    @can('can-see-all-users', $data)
    <div class="container">
        <h2 align="center"> Lexicon's Users </h2>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Thai Name</th>
                    <th scope="col">Nickname</th>
                    <th scope="col">Profile</th>
                    <th scope="col">Actions</th>
                    
                </tr>
            </thead>
            <tbody>
            {{-- to show data, will use @foreach loop --}}
                @foreach ($data as $row) {{-- เอาขอมูลมาจากตัวแปรอาเรย์ $data ในController แล้วก็ให้โชว์as $row โชว์ทีละตัว--}}
                    <tr>
                        <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{  $row->firstname }}</td>
                            <td>{{ $row->surname }}</td>
                            <td>{{ $row->thai_name }}</td>
                            <td>{{ $row->nickname }}</td> 
                            <td>
                                <a href="{{ route('user.show', $row->id) }}" class="btn btn-outline-secondary">Profile</a>
                            </td>
                            {{-- edit --}}
                            <td>
                                <a href="{{ route('user.edit', $row->id)}} " class="btn btn-outline-secondary">Edit</a>
                            </td>
                            {{-- delete --}}
                            <td>
                                <form action="{{ route('user.destroy', $row->id) }}" method="POST">
                                    @csrf @method('DELETE')
                                    <input type="submit" value="Delete" data-name="{{ $row->firstname }}" class="btn btn-outline-danger deleteForm"
                                    onclick="return confirm('Do you want to delete {{$row->firstname}} ?')">
                                </form>
                            </td>
                            
                    </tr>
                @endforeach
                   
            </tbody>
        </table>
    </div>
    @endcan
@endsection

resources/views/user/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                {{-- <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif --}}

            <div class="container bootstrap snippets bootdey">
                <div class="panel-body inf-content">
                    <div class="row">
                        
                        <div class="col-md-8 pt-4">
                            <div class="text-center font-weight-bold">{{ $user->nickname }}'s Information</div><br>
                                <div class="table-responsive">
                                    <table class="table table-user-information">
                                        <tbody>
                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">First Name</span></td>
                                                <td class="text-sm-left">{{$user->firstname}}</td>
                                            </tr>

                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Last Name</span></td>
                                                <td class="text-sm-left">{{$user->surname}}</td>
                                            </tr>

                                            <tr>
                                                <td><span class="font-weight-bold text-primary">First day at Lexicon</span></td>
                                                <td class="text-sm-left">{{$user->first_day_of_work}}</td>
                                            </tr>

                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Fullname (Thai)</span></td>
                                                <td class="text-sm-left">{{$user->thai_name}}</td>
                                            </tr>

                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Nickname</span></td>
                                                <td class="text-sm-left">{{$user->nickname}}</td>
                                            </tr>

                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Date of Birth</span></td>
                                                <td class="text-sm-left">{{$user->date_of_birth}}</td>
                                            </tr>

                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Mobile Phone</span></td>
                                                <td class="text-sm-left">{{$user->phone_number}}</td>
                                            </tr>

                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Email Address</span></td>
                                                <td class="text-sm-left">{{$user->email}}</td>
                                            </tr>

                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Line ID</span></td>
                                                <td class="text-sm-left">{{$user->line_id}}</td>
                                            </tr>

                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Department</span></td>
                                                <td class="text-sm-left">{{ ucfirst(str_replace('-', ' ', $user->department)) }}</td>
                                            </tr>
                                            
                                            <tr>        
                                                <td><span class="font-weight-bold text-primary">Emergency Contact</span></td>
                                                <td class="text-sm-left">{{$user->emergency_name}}</td>
                                                <td class="text-sm-left">{{$user->emergency_number}}</td>
                                            </tr>


                                        </tbody>
                                    </table>
                                </div> {{-- table-responsive --}}
                        </div> {{--col-md-8 pt-4--}}
                        
                        <div class="col-md-4 py-3">
                            @switch ($user)
                                    @case ($user->isAdmin())
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('user.edit', $user->id) }}">Edit Profile</a>
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('list-request') }}"> My Requests</a>
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('request.create') }}"> Request Leave</a>
                                        <a type="button" class="mt-3 btn btn-outline-info btn-sm btn-block" href="{{ route('user.index') }}">All Users</a>
                                        <a type="button" class="mt-3 btn btn-outline-info btn-sm btn-block" href="{{ route('requests.index') }}">All Requests</a>
                                        <a type="button" class="mt-3 btn btn-outline-success btn-sm btn-block" href="{{ route('leave-type') }}">All Leave Types</a>
                                        {{-- <a type="button" class="mt-3 btn btn-outline-success btn-sm btn-block" href="{{ route('create-leave-type') }}">Create a Leave Type</a> --}}
                                    @break

                                    @case ($user->isHr())
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('user.edit', $user->id) }}">Edit Profile</a>
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('list-request') }}"> My Requests</a>
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('request.create') }}"> Request Leave</a>
                                        <a type="button" class="mt-3 btn btn-outline-info btn-sm btn-block" href="{{ route('requests.index') }}">All Requests</a>

                                    @break

                                    @case ($user->isManager())
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('user.edit', $user->id) }}">Edit Profile</a>
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('list-request') }}"> My Requests</a>
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('request.create') }}"> Request Leave</a>
                                        <a type="button" class="mt-3 btn btn-outline-info btn-sm btn-block" href="{{ route('team-request') }}"> Team Requests</a>
                                        
                                    @break

                                    @case ($user->isUser())
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('user.edit', $user->id) }}">Edit Profile</a>
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('list-request') }}"> My Requests</a>
                                        <a type="button" class="mt-3 btn btn-outline-secondary btn-sm btn-block" href="{{ route('request.create') }}"> Request Leave</a>
                                    @break
                                @endswitch
                                                       
                        </div> {{--col-md-4 pt-3--}}
                    
                </div>

                {{-- balance table --}}
                <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Type</th>
                        <th scope="col" class="text-center">Used</th>
                        <th scope="col" class="text-center">Available</th>
                        <th scope="col" class="text-center">Allowance</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($types as $type)
                    <tr>
                        <th scope="row">{{$type->name}}</th>
                        <th scope="row" class="text-center">{{$type->used_days}}</th>
                        <th scope="row" class="text-center">{{$type->allowance -$type->used_days}}</th>
                        <th scope="row" class="text-center">{{$type->allowance}}</th>
                    </tr>
                    @empty
                    <tr>
                        <th scope="row" colspan="4" class="text-center">Nothing</th>
                    </tr>
                    @endforelse
            </div>
            </div> {{-- container bootstrap snippets bootdey--}}
        </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/team-index.blade.php
@can('can-view-team', $data)
@extends('layouts.app')

@section('content')
    
    <div class="container">
        <h2  class="text-uppercase" align="center"> {{ __('Team') }} </h2>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">No.</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Thai Name</th>
                    <th scope="col">Nickname</th>
                    <th scope="col">Profile</th>
                    
                </tr>
            </thead>
            <tbody>
            {{-- to show data, will use @foreach loop --}}
                @foreach ($data as $row) {{-- เอาขอมูลมาจากตัวแปรอาเรย์ $data ในController แล้วก็ให้โชว์as $row โชว์ทีละตัว--}}
                    <tr>
                       <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{  $row->firstname }}</td>
                            <td>{{ $row->surname }}</td>
                            <td>{{ $row->thai_name }}</td>
                            <td>{{ $row->nickname }}</td> 
                            <td>
                                <a href="{{ route('user.show', $row->id) }}" class="btn btn-outline-secondary">Profile</a>
                            </td>
                            {{-- <td>
                                <a href="{{ route('user.edit', $row->id)}} " class="btn btn-success">Edit</a>
                            </td>

                            <td>
                                
                                <form action="{{ route('user.destroy', $row->id) }}" method="POST">
                                    @csrf @method('DELETE')
                                    <input type="submit" value="Delete" data-name="{{ $row->firstname }}" class="btn btn-danger deleteForm"
                                    onclick="return confirm('Do you want to delete {{$row->firstname}} ?')">
                                </form>
                                
                            </td> --}}
                            
                    </tr>
                @endforeach
                   
            </tbody>
        </table>
    </div>
    
@endsection
@endcan